### ISSUE TITLE
Notify on syncing

### ISSUE THREAD

**Issue by Generator** [LyzardKing/grive-indicator#1]
Add options to notify on syncing files, something like:
> Uploading foobar...  

> Downloading foobar...  

> foobar removed...

**Comment by LyzardKing** [comment]
@Generator There's a branch with that functionality now.
It's a setting in the Preferences window.
Ideally it would be nice to add an item in the menu with the latest changed items

**Comment by LyzardKing** [comment]
It's an option in master now.
