### ISSUE TITLE
ERROR: Missing grive in PATH

### ISSUE THREAD

**Issue by pyro12** [LyzardKing/grive-indicator#11]
Forgive me if this is user-error, I am trying to run grive-indicator from the unzipped master  folder I placed in my home directory.

I keep getting the error: ERROR: Missing grive in PATH

I have grive2 installed (using the api ID and SECRET [workaround](https://github.com/vitalif/grive2/issues/287#issuecomment-558288038)).  grive is in /usr/bin/, which is most definitely in my $PATH.

I also tried the snap install, but I can't make sense of it.

```
desktop:~/grive-indicator-master$ bin/grive-indicator 

(grive-indicator:16174): Gtk-WARNING **: 10:51:04.092: Can't set a parent on widget which has a parent

(grive-indicator:16174): Gtk-WARNING **: 10:51:04.092: Can't set a parent on widget which has a parent

(grive-indicator:16174): Gdk-CRITICAL **: 10:51:04.231: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
INFO: Revisions active
ERROR: Missing grive in PATH


```

**Comment by LyzardKing** [comment]
I pushed an update that should make the debug error more useful..
If you could try again then print the error like in your previous post

**Comment by LyzardKing** [comment]
The issue might be that the path to the sync folder has not been saved properly in ~/.config/grive-indicator.conf

**Comment by pyro12** [comment]
desktop:~/grive-indicator-master$ bin/grive-indicator 

```
(grive-indicator:17938): Gtk-WARNING **: 11:51:05.613: Can't set a parent on widget which has a parent

(grive-indicator:17938): Gtk-WARNING **: 11:51:05.613: Can't set a parent on widget which has a parent

(grive-indicator:17938): Gdk-CRITICAL **: 11:51:05.751: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
INFO: Revisions active
ERROR: Missing grive in PATH: [Errno 2] No such file or directory: '': ''
```
Manually setting the path to the sync folder appears to have resolved the issue. 
```
[DEFAULT]
dark = true
time = 30
revisions = true
folder = /home/me/Grive           
upload_speed = 0
download_speed = 0
show_notifications = false
```

Thank you for your time.

**Comment by LyzardKing** [comment]
Good to know that it works..
I guess I have to fix the initial configuration. ;)
Thanks for the info!
