### ISSUE TITLE
Preferences/Settings

### ISSUE THREAD

**Issue by vlig** [LyzardKing/grive-indicator#4]
1. Pressing **Update .griveignore** button opens it in Wine's Notepad.exe))) Although double click on .griveignore in Dolphin opens it in Kate as expected.
2. Ugly white-on-yellow warning:
![_20180318_164954](https://user-images.githubusercontent.com/19915584/37566742-5ba716a4-2ace-11e8-8750-b337059f4bbf.png)

I'm using KDE Plasma 5 (Breeze-dark theme) on Arch Linux, all are up to date.

**Comment by LyzardKing** [comment]
I believe the first is an issue with the default application selected to open text files...
Regarding the second issue (yellow background) it was only tested on the ubuntu mate default theme..
I'm considering replacing that warning with a popup...

**Comment by LyzardKing** [comment]
Fixed with the latest commit.
