### ISSUE TITLE
Can not include only ONE folder in sync

### ISSUE THREAD

**Issue by vlig** [LyzardKing/grive-indicator#5]
Please help me to sync only one folder and exclude ALL others files and folders. Tried to reinstall with no luck.

**Comment by LyzardKing** [comment]
I believe you could use griveignore for that:
https://github.com/vitalif/grive2#griveignore

you could exclude everything except what you want to sync (I'm not sure how it works thought...)

**Comment by vlig** [comment]
```
!foldername
*
```
works fine, thanks!

**Comment by LyzardKing** [comment]
Great! I'll leave a note in the readme!
